# Generated by Django 2.2.24 on 2021-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211011_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='CREATED_ATT',
            field=models.DateField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='UPDATED',
            field=models.DateField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
