# Generated by Django 2.2.24 on 2021-10-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211011_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='CREATED_ATT',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='UPDATED',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
