# Generated by Django 2.2.24 on 2021-10-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211011_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='CREATED_ATT',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='UPDATED',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
