# Generated by Django 2.2.24 on 2021-10-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211011_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='CREATED_ATT',
            field=models.IntegerField(verbose_name='2000-07-04'),
        ),
        migrations.AlterField(
            model_name='location',
            name='UPDATED',
            field=models.IntegerField(verbose_name='2000-07-04'),
        ),
    ]
