# Generated by Django 2.2.24 on 2021-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211011_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='ID_DATA',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='CREATED_ATT',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='ID_LOCALIZACAO',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='UPDATED',
            field=models.IntegerField(),
        ),
    ]
